[versions]
java = "17"
checkstyle = "10.14.2"
jacoco = "0.8.11"
junit = "5.10.2"
spotbugs = "4.8.3"

[plugins]
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version = "1.30.0" }
spotbugs = { id = "com.github.spotbugs", version = "6.0.7" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }

[libraries]
apiGuardian = "org.apiguardian:apiguardian-api:1.1.2"
assertJ = "org.assertj:assertj-core:3.25.3"
cthingAnnots = "org.cthing:cthing-annotations:1.0.0"
cthingProjectVersion = "org.cthing:cthing-projectversion:1.0.0"
escapers = "org.cthing:escapers:1.0.0"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitLauncher = "org.junit.platform:junit-platform-launcher:1.10.2"
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
spotbugsContrib = "com.mebigfatguy.sb-contrib:sb-contrib:7.6.4"
